from PIL import Image

THRESHOLD = 200

def png_to_rle(png_path, rle_path):
    img = Image.open(r"C:\Users\JOY\Desktop\태민이 휴대폰\⟪👨🏻‍💻태민파일✨⟫\작품모음\태민작품\⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 1024x1024px 원년 logo⟫.png").convert("L")
    img = img.resize((314, 314))
    w, h = img.size
    px = img.load()

    body = ""
    for y in range(h):
        last = None
        count = 0
        for x in range(w):
            cell = 'o' if px[x, y] < THRESHOLD else 'b'
            if cell == last:
                count += 1
            else:
                if last:
                    body += (str(count) if count > 1 else '') + last
                last = cell
                count = 1
        body += (str(count) if count > 1 else '') + last
        body += "$"
    body += "!"

    header = f"""#N ⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 원년 314x314px life of game logo⟫
#W Origin website: https://crispiest-crunchingly-dani.ngrok-free.dev/
#M Made by Golly : https://golly.sourceforge.io/webapp/golly.html#find
#C Eternal Core Calendar
#Y Gen : AC 2026
#M Observer : Joyce
#O Generated by Taemin's Integrated Analyzer
#C Multiverse Empire Life World
#B best of ⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 원년 life of game logo⟫
x = {w}, y = {h}, rule = B3/S23
"""

    with open(r"C:\Users\JOY\Desktop\태민이 휴대폰\⟪👨🏻‍💻태민파일✨⟫\파이썬 작품\Python Conway's Game of Life (pettens & python files)\Python Conway's Game of Life (pettens & python files)\⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 원년 314x314px life of game logo⟫ 004.rle", "w", encoding="utf-8") as f:
        f.write(header + body)

png_to_rle(r"C:\Users\JOY\Desktop\태민이 휴대폰\⟪👨🏻‍💻태민파일✨⟫\작품모음\태민작품\⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 1024x1024px 원년 logo⟫.png", r"C:\Users\JOY\Desktop\태민이 휴대폰\⟪👨🏻‍💻태민파일✨⟫\파이썬 작품\Python Conway's Game of Life (pettens & python files)\Python Conway's Game of Life (pettens & python files)\⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 원년 314x314px life of game logo⟫ 005.rle")
