from PIL import Image

# ===== 설정 =====
IMAGE_PATH = r"C:\Users\JOY\Desktop\태민이 휴대폰\⟪👨🏻‍💻태민파일✨⟫\태민작품\⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 1024x1024px 원년 logo⟫.png"   # ← 변환할 이미지 파일
X, Y = 314, 314
RULE = "B3/S23"
THRESHOLD = 100  # RGB 합 기준

# ===== 이미지 로드 =====
img = Image.open(IMAGE_PATH).convert("RGB")
img = img.resize((X, Y))  # 안전용

# ===== 픽셀 → Life 셀 =====
grid = []
for y in range(Y):
    row = []
    for x in range(X):
        r, g, b = img.getpixel((x, y))
        alive = (r + g + b) > THRESHOLD
        row.append('o' if alive else 'b')
    grid.append(row)

# ===== RLE 압축 =====
def rle_encode_row(row):
    result = ""
    count = 1
    for i in range(1, len(row)):
        if row[i] == row[i-1]:
            count += 1
        else:
            result += (str(count) if count > 1 else "") + row[i-1]
            count = 1
    result += (str(count) if count > 1 else "") + row[-1]
    return result

# ===== RLE 본문 생성 =====
body_lines = []
for row in grid:
    body_lines.append(rle_encode_row(row) + "$")

body = "\n".join(body_lines)
body = body.rstrip("$") + "!"

# ===== 최종 RLE =====
rle = f"""#N ⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 원년 1024x1024px life of game logo⟫
#O Generated by Python (ChatGPT 협업)
#C RGB sum > {THRESHOLD} → alive(o)
x = {X}, y = {Y}, rule = {RULE}
{body}
"""

# ===== 파일 저장 =====
with open("⟪大韓 Multiverse Empire • Established 1995 • 건양(建陽) 원년 1024x1024px life of game logo⟫.rle", "w", encoding="utf-8") as f:
    f.write(rle)

print("✅ RLE 생성 완료: multiverse_empire_314x314.rle")
